name: Figma Code Connect, publish both React and Web component configs

on:
  push:
    branches:
      - main

jobs:
  code-connect:
    name: Code Connect - ${{ matrix.package }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package:
          - ibm-products
          - ibm-products-web-components
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Setup Node.js
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '20.19.5'
          cache: yarn
      - name: Cache dependencies
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # 4.3.0
        with:
          path: '**/node_modules'
          key: build-modules-${{ runner.os }}-${{ hashFiles('yarn.lock') }}
      - name: Install
        run: yarn
      - name: Run publish
        working-directory: packages/${{ matrix.package }}
        run: npx figma connect publish
        env:
          FIGMA_ACCESS_TOKEN: ${{ secrets.FIGMA_ACCESS_TOKEN }}
