# Deploy staging storybook environment from release branch to Github Pages
name: Deploy staging storybook

# Gets triggered every time a release candidate has been published from the `release-base` workflow
# or can be manually triggered
on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-staging-storybook]

jobs:
  deploy-staging-storybook:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: '0'
          ref: ${{ github.event.client_payload.branch }}
      - name: Free disk space
        uses: ./.github/actions/free-disk-space

      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages and storybook
        run: |
          yarn build
          yarn storybook-wc:build

      # Deploy to staging Github Pages using `gh-pages` package
      - name: Prepare combined staging directory with clean URL paths
        run: |
          mkdir -p staging-dist/react
          cp -r packages/ibm-products/storybook-static/* staging-dist/react

          mkdir -p staging-dist/web-components
          cp -r packages/ibm-products-web-components/storybook-static/* staging-dist/web-components

      # Set authenticated Git remote
      - name: Set authenticated Git remote
        run:
          git remote set-url origin https://git:${{ secrets.GITHUB_TOKEN
          }}@github.com/${{ github.repository }}.git

      - name: Deploy both Storybooks to GitHub Pages (gh-pages/staging)
        run: |
          npx gh-pages -d staging-dist \
            -u "github-actions-bot <support+actions@github.com>" \
            --dest staging \
            --message "chore(deploy): deploy React and Web Components Storybooks to staging"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
