# Deploy production storybook environment from release branch to Github Pages
name: Deploy production storybook

# This workflow is triggered from the `release-base` workflow when a full release
# has been successfully completed
on:
  workflow_dispatch:
  repository_dispatch:
    types: [deploy-latest-storybook]

jobs:
  deploy-latest-storybook:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    permissions:
      contents: write
    steps:
      # Checkout release branch to build storybook
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
        with:
          fetch-depth: '0'
          ref: ${{ github.event.client_payload.branch }}
      - name: Free disk space
        uses: ./.github/actions/free-disk-space
      - name: Use Node.js version from .nvmrc
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f # v6.1.0
        with:
          node-version-file: '.nvmrc'
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install --immutable
      - name: Build storybook
        run: |
          yarn build
          yarn storybook-wc:build
      # Set authenticated Git remote
      - name: Set authenticated Git remote
        run:
          git remote set-url origin https://git:${{
          secrets.GITHUB_TOKEN}}@github.com/${{ github.repository }}.git
      # Deploy to staging Github Pages using `gh-pages` package
      - name: Prepare latest directory
        run: |
          mkdir -p latest-dist/react
          cp -r packages/ibm-products/storybook-static/* latest-dist/react

          mkdir -p latest-dist/web-components
          cp -r packages/ibm-products-web-components/storybook-static/* latest-dist/web-components

      - name: Deploy latest Storybooks to gh-pages/latest
        run: |
          npx gh-pages -d latest-dist \
            -u "github-actions-bot <support+actions@github.com>" \
            --dest latest \
            --message "chore(deploy): deploy React and Web Components Storybooks to latest"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
