name: Process saved PR data and apply appropriate labels

# We have access to repo secrets from here. If the `Received PR review` workflow has completed
# it means there has been a workflow artifact created with the data we need to apply the appropriate 
# review labels from the custom action used from this workflow
on:
  workflow_run:
    workflows: ['Received PR review']
    types:
      - completed

jobs:
  upload:
    runs-on: ubuntu-latest
    if: >
      github.event.workflow_run.event == 'pull_request_review' &&
      github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - uses: ./actions/add-review-labels
        with:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          APP_INSTALLATION_ID: ${{ secrets.APP_INSTALLATION_ID }}
