name: v1 minor release
run-name:
  ${{ inputs.type }} - dry-run:${{ inputs.dry-run }}

on:
  workflow_dispatch:
    inputs:
      type:
        required: true
        description: 'Specify the type of release'
        type: choice
        default: first minor rc
        options:
          - full minor release
          - first minor rc
          - subsequent rc
      dry-run:
        required: true
        description: 'Run dry run?'
        type: boolean
        default: true

jobs:
  Release:
    uses: ./.github/workflows/release-workflow.yml
    with:
      type: ${{ inputs.type }}
      dry-run: ${{ inputs.dry-run }}
    secrets: inherit
