# Publish minor or patch releases, both rc (release candidates) and full stable releases
name: Release start - minor / patch
run-name: ${{ inputs.type }} - dry-run:${{ inputs.dry-run }}

on:
  workflow_dispatch:
    inputs:
      semver-type:
        description: 'Specify the type of semver release'
        required: true
        type: choice
        default: minor
        options:
          - minor
          - patch
      type:
        description: 'Specify the type of release (stable, preview, etc.)'
        required: true
        type: choice
        default: first rc
        # Full release (ie. v2.0.0 -> v2.1.0)
        # First RC (ie. v2.0.0 -> v2.1.0-rc.0)
        # Subsequent RC (ie v2.1.0-rc.0 -> v2.1.0-rc.1)
        options:
          - full release
          - first rc
          - subsequent rc
      dry-run:
        # Check dry run to test run lerna and confirm package version bumps
        required: true
        description: 'Run dry run?'
        type: boolean
        default: true

jobs:
  Release:
    # trigger the input data to the `release-base` workflow and trigger it
    uses: ./.github/workflows/release-base.yml
    with:
      semver-type: ${{ inputs.semver-type }}
      type: ${{ inputs.type }}
      dry-run: ${{ inputs.dry-run }}
    secrets: inherit
