name: Triages labeled issues by adding them to a specific project field

on:
  issues:
    types: [ labeled ]

jobs:
  move-ts-issues:
    if: ${{contains(github.event.label.name, format('area{0} typescript', ':'))}}
    uses: carbon-design-system/.github/.github/workflows/move-issue-to-project-and-set-fields.yml@main
    with:
      field: 'Area'
      field_option: 'üü¶ Typescript'
      project_number: '65'
    secrets: inherit
  move-migration-issues:
    if: ${{contains(github.event.label.name, format('area{0} migration ‚û°Ô∏è', ':'))}}
    uses: carbon-design-system/.github/.github/workflows/move-issue-to-project-and-set-fields.yml@main
    with:
      field: 'Area'
      field_option: 'üó∫ Migration'
      project_number: '65'
    secrets: inherit
  move-a11y-issues:
    if: ${{contains(github.event.label.name, format('type{0} a11y ‚ôø', ':'))}}
    uses: carbon-design-system/.github/.github/workflows/move-issue-to-project-and-set-fields.yml@main
    with:
      field: 'Area'
      field_option: '‚ôøÔ∏è Accessibility'
      project_number: '65'
    secrets: inherit
