name: Triages labeled issues by adding them to a specific project field

on:
  issues:
    types: [ labeled ]

jobs:
  move-ts-issues:
    if: ${{contains(github.event.label.name, format('area{0} typescript', ':'))}}
    uses: ./.github/workflows/move-issue-to-project-and-set-fields.yml
    with:
      field: 'Area'
      field_option: 'ğŸŸ¦ Typescript'
      project_number: '65'
    secrets: inherit
  move-migration-issues:
    if: ${{contains(github.event.label.name, format('area{0} migration â¡ï¸', ':'))}}
    uses: ./.github/workflows/move-issue-to-project-and-set-fields.yml
    with:
      field: 'Area'
      field_option: 'ğŸ—º Migration'
      project_number: '65'
    secrets: inherit
  move-a11y-issues:
    if: ${{contains(github.event.label.name, format('type{0} ally â™¿', ':'))}}
    uses: ./.github/workflows/move-issue-to-project-and-set-fields.yml
    with:
      field: 'Area'
      field_option: 'â™¿ï¸ Accessibility'
      project_number: '65'
    secrets: inherit
